### PR TITLE
Update fr.ts

### PR DESCRIPTION
**Pull request by lyonelf**

### CODE REVIEW

**Comment by lyonelf** [comment]
Possible to put those projects in Crowdin, to follow easily translation updates?

**Comment by DanielProg39** [comment]
You can see the point [here](https://github.com/FilenCloudDienste/filen-mobile/issues/115#issuecomment-1369104529)

**Comment by Dwynr** [comment]
Formatting has changed, simply re-add the updated strings :)

**Comment by lyonelf** [comment]
can you xplain me what and how?

**Pull request closed without merging**
